### ISSUE TITLE
Has the scheduler been removed for good?

### ISSUE THREAD

**Issue by draven72** [hoebat/hara#1]
I've been hara.io.scheduler for the past few years and found it really useful. I noticed it's no longer in the library, has been removed permanently?

**Comment by zcaudate** [comment]
Hi Ben,

Thanks for the message. I'm in the process of cleaning up the libraries as I've changed the way libraries are being deployed. It's still there, I need to hook everything up in order to get it working again.

**Comment by draven72** [comment]
Thanks

**Comment by devth** [comment]
I noticed the docs site is down too: https://docs.caudate.me/hara/hara-io-scheduler.html

**Comment by zcaudate** [comment]
docs are up: https://zcaudate.github.io/hara/
