### ISSUE TITLE
The docs are not working for hara

### ISSUE THREAD

**Issue by abhi18av** [hoebat/hara#2]
Hi @zcaudate 

I was wondering what happened to the libraries of `hara` and `lucid` . I came to rely on these extensively but now I'm unable to locate their documentation at all.

Could you please update me

**Comment by zcaudate** [comment]
@abhi18av.

Thanks for the message. I'm working on that at the moment. Which libraries do you need documentation to?

**Comment by abhi18av** [comment]
Oh, I see.

There are plenty which I've come to use by default , these are a few 

```
im.chit/lucid.distribute
im.chit/lucid.git
im.chit/lucid.graph
im.chit/lucid.inception
im.chit/lucid.legacy
im.chit/lucid.mind
im.chit/lucid.package
im.chit/lucid.publish
im.chit/lucid.query
im.chit/lucid.space
im.chit/lucid.system
im.chit/lucid.unit
```

@zcaudate , please do let me know on this issue when you're done with the renovation :)

**Comment by zcaudate** [comment]
no worries. will do.

**Comment by zcaudate** [comment]
@abhi18av: I've published the docs here: https://zcaudate.github.io/hara/. I've merged lucid into hara so am sorting out a couple of things.

I'm curious - which features do you actually use from lucid?

**Comment by abhi18av** [comment]
Oh, I mostly use `mind` etc from `lucid`.

Thanks for the quick work here @zcaudate! 👍

**Comment by abhi18av** [comment]
And also, `lucid.query` package

**Comment by zcaudate** [comment]
I see. 

I don't want to release the query part of it at this stage as it's undergone quite a lot of change and needs to be tested.

the macros - `.?, .*, etc...` are wrappers around `hara.object.query` so it's pretty easy to define.
