### ISSUE TITLE
Consider renaming `hara.data/assoc-if`

### ISSUE THREAD

**Issue by WhittlesJr** [hoebat/hara#3]
Other libraries (like [encore](https://github.com/ptaoussanis/encore/blob/master/src/taoensso/encore.cljx#L1082)) call this `assoc-some`, which to me is clearer. 

`assoc-if` would make more sense to me if it took a predicate, like `(assoc-if even? {} :a 1 :b 2 :c 3 => {:b 2}`

I'd understand if this breaking change would be too disruptive, though.

**Comment by WhittlesJr** [comment]
Oh, ok. Honestly I got excited when I found your project because it _did_ have such a large collection of functions. I hate having my own util namespace of common generic functions, and there are a ton of other util repos out there that don't cover all the bases. I've thought about creating a project that does nothing but collect all of these functions from all of these other util repos by def'ing them together into one namespace. But that's also kind of annoying, haha. 

`map-keys` and `map-vals` are the two that show up most commonly in other projects (encore, medley, etc.)

**Comment by zcaudate** [comment]
Yeah, tell me about it. That's the inherent problem with having too much choice. It depends on what the goal is. I tend to trade optimisation for range and modularity. It's a bit of work to catalog the functions but I'd much rather having better code reuse and less redundancy.

Going back to the `-if`, `-some` thing. It'll be great to get some advice.

**Comment by WhittlesJr** [comment]
Definitely. Here are some other thoughts I had: `assoc-some` makes sense to me, although I could also understand something like `assoc-nnil`. Or I could also understand just having the `(assoc-if pred m & kvs)` behavior I mentioned, and just saying `(assoc-if some? ...)` 

Do you have other contributors / consumers of this library that should chime in?

**Comment by zcaudate** [comment]
Nope. It's just me.

- I like the `-nnil` suffix. It's clear. If we go with that, there will be 7 functions changed.
- I'd prefer to not use `some` because there are functions like `assoc-in-if` that only takes one pair
- I agree that `-if` suffix taking a predicate is good. It'll be trivial to add `assoc-if` and maybe `merge-if`
- For more generalised cases, I would rather go with something more generic - a little bit like `spector`'s transform function.

There's one problem though. 

- The suffix `-nil` is used to merge values from the second map into the first if the entry for the first map is nil. ie. 

```
(merge-nil {:a 1} {:b 2})
=> {:a 1 :b 2}

(merge-nil {:a 1} {:a 2})
=> {:a 1}

(assoc-in-nil {} [:a :b] 2)
=> {:a {:b 2}}

(assoc-in-nil {:a {:b 1}} [:a :b] 2)
=> {:a {:b 1}}
```

if the `-nnil` suffix is used, I'd like to change the `-nil` suffix to something else otherwise it would get confusing.

**Comment by WhittlesJr** [comment]
Hmm, yeah `merge-nil` et al. are a little unclear at first.

Encore calls your `assoc-nil` function `assoc-nx`, which is even less clear.

Some thoughts:
  - `merge-new-keys`
  - `merge-new`
  - `merge-if-new`
  - `merge-added`
  - `merge-additional`
  - `merge-unique`
  - `merge-no-squash`

Any of those sound decent, or give you any ideas for something decent?

**Comment by WhittlesJr** [comment]
Oh, although that terminology is assuming that the key doesn't exist in the merged map. But you probably want it to merge even if it `contains?` the key but the value is `nil`?

**Comment by WhittlesJr** [comment]
Well, then the `assoc-some` terminology helps to distinguish, but I know you said you don't like that.

In my brain, the following makes sense:

```
(defn reduce-kvs [rf init kvs]
  (reduce (fn [acc [k v]] (rf acc k v)) init (partition-all 2 kvs)))

(defn assoc-if
  "Assocs each kv if (pred value) is true

   (assoc-if odd? {:a 1} :b 2 :c 3)
   => {:a 1 :c 3}"
  ([pred m k v      ] (if (pred v) (assoc m k v) (or m {})))
  ([pred m k v & kvs]
   (reduce-kvs
    (fn [m k v] (assoc-if pred m k v))
    (assoc-if pred m k v)
    kvs))

  ([pred m kvs]
   (apply (partial assoc-if pred m) kvs)))

(defn assoc-nil
  "Assocs each kv if the value in the original map is nil or nonexistant

   (assoc-nil {:a 1} :b 2)
   => {:a 1 :b 2}

   (assoc-nil {:a 1 :b nil} :a 2 :b 2)
   => {:a 1 :b 2}"
  {:added "3.0"}
  ([m k v      ] (if (some? (get m k)) (or m {}) (assoc m k v)))
  ([m k v & kvs]
   (reduce-kvs
    (fn [m k v] (assoc-nil m k v))
    (assoc-nil m k v)
    kvs))

  ([m kvs]
   (apply (partial assoc-nil m) kvs)))

(defn assoc-new
  "Assoc each kv if the original map does not contain the key

   (assoc-new {:a 1} :b 2)
   => {:a 1 :b 2}

   (assoc-new {:a 1 :b nil} :a 2 :b 2 :c 3)
   => {:a 1 :b nil :c 3}"
  ([m k v      ] (if (contains? m k) (or m {}) (assoc m k v)))
  ([m k v & kvs]
   (reduce-kvs
    (fn [m k v] (assoc-new m k v))
    (assoc-new m k v)
    kvs))

  ([m kvs]
   (apply (partial assoc-new m) kvs)))

(def assoc-some
  "Assoc each kv if its value is not nil.

   (assoc-some {:a 1} :b 2 :c nil)
   => {:a 1 :b 2}"
  (partial assoc-if some?))

```

**Comment by WhittlesJr** [comment]
If you like that scheme, I'd be happy to write up a PR for this and the merge-* functions as well

**Comment by zcaudate** [comment]
- Yes to 1.
- For 5, can the function be renamed to `reduce-kv-array` or something a little bit more verbose.
- If we're going with the `-some` suffix, I don't see the need to change the `-nil` suffix
- Regarding the `-over-nil` and `-new` functionalities. For practical purposes, I've more or less associated `{:a nil}` and `{}` as being equivalent. It just makes things a lot easier to reason about.
- Yes to `merge-if` and `merge-some/merge-nnil`. 
- Either a PR or a Gist is fine, though I can't merge it directly as this repo dumps out part of the code from a private one. I'll have to do a copy and paste for the time being.
- It'll be great if you can add the test's with a `:refer` meta - https://github.com/zcaudate/hara/blob/develop/test/hara/data/base/map_test.clj#L6-L8
- don't worry about the docstrings, they are taken from the tests.

**Comment by WhittlesJr** [comment]
Alrighty. 

In my world, {:a nil} and {} often mean very different things, so in my case I would need the distinction. 

I started working on a PR, but since you have your own way of doing things, I'll just send you what I have and you can do whatever you want with it. It only has the `assoc` versions, though.

**Comment by WhittlesJr** [comment]
Er, actually, the gist I sent you has pretty much everything that matters. Do you just want to copy/paste/edit out of that?

**Comment by zcaudate** [comment]
> In my world, {:a nil} and {} often mean very different things, so in my case I would need the distinction.

Can you give an example?

**Comment by zcaudate** [comment]
> Er, actually, the gist I sent you has pretty much everything that matters. Do you just want to copy/paste/edit out of that?

I'd prefer it if we can get it right. I'm really pedantic about foundational-level stuff especially as it impacts on everything else.
on everything else.

**Comment by WhittlesJr** [comment]
In some parts of some of my projects, `nil` can be meaningful as a value, and can preclude other values from being assoc'd onto the map. If a key was specifically assoc'd with `nil` as its value, I've run into cases where that means nothing else should squash it, so I would use `assoc-new`. Its more incidental than an intentional pattern, of course, since you're right in that it's potentially harder to reason about.

As for my contribution, frankly, the way hara is structured presents some barriers for me, because your build environment is seemingly not reproducible or deterministic from my perspective. It doesn't make much sense for me to go through the effort to write up a working, merge-able PR if you're not going to incorporate it by merging.

I don't want to drain any more of your time if our workflows aren't compatible... it sounds like hara is a really good fit for your own projects, and I don't want to disrupt your use of it if it's not going to make sense for me to use it myself.

**Comment by zcaudate** [comment]
> nil can be meaningful as a value, and can preclude other values from being assoc'd onto the map

Can you give an example?

> It doesn't make much sense for me to go through the effort to write up a working, merge-able PR if you're not going to incorporate it by merging.

I understand.

**Comment by WhittlesJr** [comment]
Usually it has to do with applying default values to a map that may contain "null" values. In my case I work with converting binary protocols into clojure structures and vis versa, and some protocols have a concept of NULL that I express as `nil`. I suppose I could always just call it `:null` or something.

**Comment by zcaudate** [comment]
Okay. You need it for instantiation. Do you have an actual code example of the type of thing that you need to write?

I've been very wary of anything OSS since an article of mine blew up https://news.ycombinator.com/item?id=15425632 a while back. I feel that clojure has evolved the way it has become due to the disproportionate number of consultancies vs product companies who have taken it onboard. Consultancies tend to compete by staying relevant. I don't like the process of vying for developer mindshare so I'm happy to keep the library closed for now.

This repo is here because there are legacy users of `hara` and I felt like a dick when I pulled everything offline. The extended list of libraries can be found here https://caudata.gitlab.io/base/

**Comment by WhittlesJr** [comment]
After some digging in my code, I  realize I don't have an actual code example, at least not a concise one. Sorry.

**Comment by zcaudate** [comment]
no worries.

**Comment by zcaudate** [comment]
[hara/data "3.0.3"] is pushed to clojars with the following changes:

- suffixes ending with `-if` are changed to `-nnil`
- suffixes ending with `-nil` are changed to `-new`
- `filter-keys` and `filter-vals` are added for map operations. `assoc-if` and other more finer-grained predicate variations can be composed by combination these methods, along with the standard `filter`

**Comment by zcaudate** [comment]
oops. it should be `[hara/base "3.0.3]` and then `(require 'hara.data)` or `(require 'hara.data.base.map)`

**Comment by WhittlesJr** [comment]
Wonderful, thank you!
