### ISSUE TITLE
scheduler - No such var: protocol.state/-create-state

### ISSUE THREAD

**Issue by Eschon** [hoebat/hara#5]
I have a clojure project that still uses https://github.com/zcaudate-me/cronj and I wanted to update it to hara/io.scheduler

But when I include `[hara/io.scheduler "3.0.2"]` in my project and try to use it I get the following error:

```
Syntax error compiling at (hara/state/base/impl.clj:37:1).
No such var: protocol.state/-create-state
```

I'm using clojure 1.10.1

I hope you can help me solve this. Let me know if you need any additional information.

**Comment by zcaudate** [comment]
Can you try `[hara/io.scheduler "3.0.5"]` to see if this has been fixed in the most recent version?

**Comment by Eschon** [comment]
I just tried the most recent version. The same problem still shows up.

**Comment by zcaudate** [comment]
thanks for letting me know. I’ll push an update in the next day or two.

**Comment by zcaudate** [comment]
I've pushed an update. Let me know if you are still having issues.

```
boot.user=> (set-env! :dependencies '[[hara/io.scheduler "3.0.6"]])
nil
boot.user=> (require 'hara.io.scheduler)
nil
```

**Comment by Eschon** [comment]
Thanks, I tried it but the error still happens for me.
I'll investigate it further and try to make a minimal example to reproduce it.

**Comment by Eschon** [comment]
Ok, I've figured it out. The problem was that I hadn't fully removed cronj and that was creating some kind of conflict. Now everything seems to be working as expected. Sorry for your inconvenience.

**Comment by zcaudate** [comment]
Ah that makes sense. The baseline libraries have changed significantly between v2 and v3 of hara.
