### ISSUE TITLE
Unbound fn on hara.function.base.memoize 

### ISSUE THREAD

**Issue by VMarkz** [hoebat/hara#7]
Im using **hara.schedule.io** to execute a anonymous function, works fine when called by REPL or `lein run`. The error occurs when a execute the app by a JAR file.

The `handler` below is something like that:

`#(prn "foo")`

`(defmethod ig/init-key ::scheduler
  [_ {:keys [cron-expression handler]}]
  (-> {:source-analyzer {:handler handler
                         :schedule cron-expression}}
      scheduler/scheduler
      scheduler/start!))`

`Caused by: java.lang.IllegalStateException: Attempting to call unbound fn: #'hara.function.base.memoize/memoize
        at clojure.lang.Var$Unbound.throwArity(Var.java:45)
        at clojure.lang.AFn.invoke(AFn.java:48)
        at hara.function.base.memoize$memoize.invokeStatic(memoize.clj:45)
        at hara.module.base.link$fn__22920.invokeStatic(link.clj:39)
        at hara.module.base.link$fn__22920.invoke(link.clj:39)
        at hara.module.base.link__init.load(Unknown Source)
        at hara.module.base.link__init.<clinit>(Unknown Source)
        ... 274 more`

Any idea why this happens only by executing with a JAR file?

**Comment by zcaudate** [comment]
By the error, it seems that the library - `hara.module.base.link` (which in a repl environment is responsible for lazy loading a namespace) cannot find a file. It may have broken when aot compiling the jar.

 Can you try explicitly requiring `hara.function.base.memoize` somewhere before the call to `scheduler/start`?

---

Note that this scheduler is unmaintained. It works but there are probably better and more efficient ones out there.

**Comment by VMarkz** [comment]
Correcting myself hehe, making the require to `hara.function.base.memoize` worked to me, but there's a detail, this require should be made before the require to `hara.io.scheduler :as scheduler`, also I used `:refer :all` on `hara.function.base.memoize`. There's no need to not use the **aot** method.
Again, thanks for the help! 😃

**Comment by zcaudate** [comment]
ah awesome. I'm glad it worked!
